name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build dependencies
        run: |
          mkdir -p libxposed
          cd libxposed
          git clone https://github.com/libxposed/api.git
          cd api
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew publishToMavenLocal
          cd ../..
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}
      - name: Build with Gradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Maven settings
        run: cp .github/workflows/settings.xml ~/.m2/settings.xml
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: ~/.m2
      - name: Prepare pages
        run: |
          mkdir -p docs
          cp -r helper/build/intermediates/java_doc_dir/release/* docs/
          mkdir -p docs/ktx
          cp -r helper-ktx/build/intermediates/java_doc_dir/release/* docs/ktx
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
